source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:SerilesJam/PrivateSpecs.git'

platform :ios, '9.0'

install! 'cocoapods',
         :disable_input_output_paths => true
inhibit_all_warnings!
use_modular_headers!

target 'JCUserService_Example' do
  pod 'JCUserService', :path => '../'

  target 'JCUserService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
