use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:SerilesJam/PrivateSpecs.git'

target 'JCUserService_Example' do
  pod 'JCUserService', :path => '../'

  target 'JCUserService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
