use_frameworks!

platform :ios, '8.0'

target 'JCUserService_Example' do
  pod 'JCUserService', :path => '../'

  target 'JCUserService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
